### ISSUE TITLE
Fix illuminate/support version for laravel +7

### ISSUE THREAD

**Issue by a3zzini** [sfwanessam/laravel-tap-payment#1]
Hello, 
Thank you for this great job, I've a little problem and I wish if you can fix it asap
The illuminate/support version is outdate compare to laravel version (+7) :
`"illuminate/support": "5.5.*|5.6.*|5.7.*|5.8.*"`

![image](https://user-images.githubusercontent.com/77169023/106816421-9f045480-6675-11eb-8213-85aef1aa50d0.png)

**Comment by sfwanessam** [comment]
Hi thank you :)  , Now we have solved the problem by launching a second version that supports the latest versions of Laravel , you can try with <code>v0.0.2</code>
