### ISSUE TITLE
Issue live

### ISSUE THREAD

**Issue by mustafaabduljalil** [sfwanessam/laravel-tap-payment#4]
I think you need to handle merchant id in live by adding it in doc

**Comment by hazemSaeed** [comment]
![image](https://user-images.githubusercontent.com/29402987/203847453-1d94ccf8-0903-43a3-a0a2-432d2a30baf5.png)
I think because of this spacing

**Comment by hazemSaeed** [comment]
It solved by me

**Comment by sfwanessam** [comment]
@hazemSaeed Your pull Request was merged , Thanks for your contribution
